### ISSUE TITLE
Add Configurable Hotkey to toggle "Home Menu"

### ISSUE THREAD

**Issue by cbartondock** [Megamouse/rpcs3#13]
Issue: The PS button currently used to trigger the (terrific) home menu is also used by many other services, e.g. steam overlay. It would be nice to open it via a hotkey as well as the PS button. 

Alternatively, the ability to "or" inputs would suffice. e.g. "Esc || PS Button". Dolphin, for example, has this capability. Thanks!

**Comment by cbartondock** [comment]
For anyone who has this issue in the future a work-around is to create a second controller config with no other buttons set except the guide button.

**Comment by Megamouse** [comment]
This is not the RPCS3 repository, it's my fork...
